server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
spring:
  datasource:
    username: root
    password: lkm99314
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useSSL=false&characterEncoding=utf8&useUncode=true&serverTimezone=Asia/Shanghai
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
  rabbitmq:
    host: 152.136.116.233
    port: 5672
    username: platform
    password: 123456
    virtual-host: /platform
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liu.entity
